CreditCardVerifier.Api/CreditCardVerifier.Web/Models/ErrorViewModel.cs
using System;

namespace CreditCardVerifier.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CreditCardVerifier.Api/CreditCardVerifier.Web/Controllers/CreditCardsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CreditCardVerifier.Web.Helpers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;

namespace CreditCardVerifier.Web.Controllers
{
    public class CreditCardsController : Controller
    {
        CreditCardApi _creditCardApi = new CreditCardApi();

        public async Task<IActionResult> Index()
        {
            List<CreditCardData> dto = new List<CreditCardData>();

            RestClient client = _creditCardApi.InitializeClient();
            var request = new RestRequest("/api/creditcard/", Method.GET);
            IRestResponse _response = client.Execute(request);

            if (_response.IsSuccessful)
            {
                var result = _response.Content;
                dto = JsonConvert.DeserializeObject<List<CreditCardData>>(result);
            }

            return View(dto);
        }

        public IActionResult Validate()
        {
                ViewBag.Validated = false;
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Validate([Bind("CardNum")] long cardNum)
        {
            CreditCardData dto = new CreditCardData();

            RestClient client = _creditCardApi.InitializeClient();
            var request = new RestRequest("/api/creditcard/" + cardNum, Method.GET);
            IRestResponse _response = client.Execute(request);

            if (_response.IsSuccessful)
            {
                var result = _response.Content;
                dto = JsonConvert.DeserializeObject<CreditCardData>(result);
            }
            ViewBag.Validated = true;
            return View(dto);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id, CardNum, Month, Year")] CreditCardData creditCardData)
        {
            if (ModelState.IsValid)
            {
                RestClient client = _creditCardApi.InitializeClient();
                var request = new RestRequest("/api/creditcard/", Method.POST);
                request.AddJsonBody(
                    new
                    {
                        CardNum = creditCardData.CardNum,
                        Month = creditCardData.Month,
                        Year = creditCardData.Year
                    });

                IRestResponse _response = client.Execute(request);
                if (_response.IsSuccessful)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(creditCardData);
        }


        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<CreditCardData> dto = new List<CreditCardData>();
            RestClient client = _creditCardApi.InitializeClient();
            var request = new RestRequest("/api/creditcard/", Method.GET);
            IRestResponse _response = client.Execute(request);

            if (_response.IsSuccessful)
            {
                var result = _response.Content;
                dto = JsonConvert.DeserializeObject<List<CreditCardData>>(result);
            }

            var creditCard = dto.SingleOrDefault(m => m.Id == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            return View(creditCard);
        }


        [HttpPost, ActionName("Put")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long id, [Bind("Id, CardNum, Month, Year")] CreditCardData creditCardData)
        {
            if (id != creditCardData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                RestClient client = _creditCardApi.InitializeClient();
                var request = new RestRequest("/api/creditcard/" + id, Method.PUT);
                request.AddJsonBody(
                    new
                    {
                        CardNum = creditCardData.CardNum,
                        Month = creditCardData.Month,
                        Year = creditCardData.Year
                    });

                IRestResponse _response = client.Execute(request);
                if (_response.IsSuccessful)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(creditCardData);
        }


        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<CreditCardData> dto = new List<CreditCardData>();
            RestClient client = _creditCardApi.InitializeClient();
            var request = new RestRequest("/api/creditcard/", Method.GET);
            IRestResponse _response = client.Execute(request);

            if (_response.IsSuccessful)
            {
                var result = _response.Content;
                dto = JsonConvert.DeserializeObject<List<CreditCardData>>(result);
            }

            var creditCard = dto.SingleOrDefault(m => m.Id == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            return View(creditCard);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            RestClient client = _creditCardApi.InitializeClient();
            var request = new RestRequest("/api/creditcard/" + id, Method.DELETE);
            IRestResponse _response = client.Execute(request);
            if (_response.IsSuccessful)
            {
                return RedirectToAction("Index");
            }

            return NotFound();
        }
    }
}

CreditCardVerifier.Api/CreditCardVerifier.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CreditCardVerifier.Web.Models;

namespace CreditCardVerifier.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CreditCardVerifier.Api/CreditCardVerifier.Web/Views/CreditCards/Create.cshtml
@model CreditCardVerifier.Web.Helpers.CreditCardData

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Credit Card</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="CardNum" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CardNum" class="form-control" />
                <span asp-validation-for="CardNum" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Month" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Month" class="form-control" />
                <span asp-validation-for="Month" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Year" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CreditCardVerifier.Api/CreditCardVerifier.Web/Views/CreditCards/Delete.cshtml
@model CreditCardVerifier.Web.Helpers.CreditCardData

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Credit Card</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.CardNum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CardNum)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Month)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Month)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

CreditCardVerifier.Api/CreditCardVerifier.Web/Views/CreditCards/Index.cshtml
@model IEnumerable<CreditCardVerifier.Web.Helpers.CreditCardData>
@using System.Text.RegularExpressions;
@using System.Security.Cryptography;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CardNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{

                        var lastDigits = item.CardNum.ToString().Substring(item.CardNum.ToString().Length - 4, 4);

                        var requiredMask = new String('*', item.CardNum.ToString().Length - lastDigits.Length);

                        var maskedString = string.Concat(requiredMask, lastDigits);
                        ViewBag.Num = Regex.Replace(maskedString, ".{4}", "$0 ");
                    }
                    @ViewBag.Num
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td> 
                    @Html.ActionLink("Delete", "Delete", "CreditCards", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>

CreditCardVerifier.Api/CreditCardVerifier.Web/Views/CreditCards/Validate.cshtml
@model CreditCardVerifier.Web.Helpers.CreditCardData

@{
    ViewData["Title"] = "Validate";
}

<h2>Validate</h2>

<h4>CreditCardData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Validate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CardNum" class="control-label"></label>
                <input asp-for="CardNum" class="form-control" />
                @if (ViewBag.Validated)
                {
                    if (Model.Validity != "Valid")
                    {
                        <span style="color:red"> @Html.DisplayFor(m => m.Validity)</span>
                    }
                    else
                    {
                        <span style="color:green"> @Html.DisplayFor(m => m.Validity)</span>
                    }

                    <div class="form-group">
                        @Html.LabelFor(m => m.CardType)
                        <div class="col-md-10">
                            @Html.DisplayFor(m => m.CardType)
                        </div>
                    </div>
                }
                <span asp-validation-for="CardNum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Validate" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CreditCardVerifier.Api/CreditCardVerifier.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CreditCardVerifier.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="CreditCards" asp-action="Validate" class="navbar-brand">Credit Card Verifier</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="CreditCards" asp-action="Validate">Verify</a></li>
                    <li><a asp-area="" asp-controller="CreditCards" asp-action="Index">Credit Cards</a></li>
                    <li><a asp-area="" asp-controller="CreditCards" asp-action="Create">Create</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CreditCardVerifier.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>